# Generated by Django 5.2.4 on 2025-07-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_joined_date_member_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
