# Generated by Django 5.2.4 on 2025-07-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_birthday_member_email_member_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="member",
            name="email",
        ),
        migrations.RemoveField(
            model_name="member",
            name="gender",
        ),
    ]
