# Generated by Django 5.2.4 on 2025-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_remove_member_birthday_remove_member_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
